name: dynamic_component_loading
description: A web app that uses AngularDart Components
version: 1.0.0

environment:
  sdk: '>=2.9.3 <3.0.0'

dependencies:
  angular: ^6.0.0

dev_dependencies:
  angular_test: ^2.3.0
  build_runner: ^1.9.0
  build_test: ^1.0.0
  build_web_compilers: ^2.10.0
  pedantic: ^1.9.0
  test: ^1.6.3
